// Typed mirrors of pult's documented JSON surfaces (schema 1), matching
// src-tauri/src/types.rs field-for-field. Schema 1 is additive-only, so
// every field here is exactly what the docs promise — extra fields a future
// pult adds are simply ignored by JSON.parse, not an error.

export interface Param {
  name: string;
  kind: "pick" | "input";
  options?: string[];
  source?: string;
  depends_on?: string[];
  default?: string | null;
  secret?: boolean;
}

export interface IncludeInfo {
  source: string;
  kind: string;
  name: string | null;
  url?: string;
  rev?: string;
  rev_kind?: string;
  resolved_sha?: string;
}

export interface CommandInfo {
  id: string;
  title: string;
  origin: string | null;
  category: string | null;
  /** Operator-facing one-liner for the board card. Additive field — may be
   *  absent or null; treat as "no description" (title-only card), not an
   *  error. */
  description?: string | null;
  params: Param[];
  check: string | null;
  interactive: boolean;
  steps: string[] | null;
}

export interface Listing {
  schema: number;
  pult_version: string;
  name: string;
  manifest: string;
  dir: string;
  run_dir: string;
  scope: string;
  trusted: boolean;
  includes: IncludeInfo[];
  commands: CommandInfo[];
}

export interface DoctorEntry {
  id: string;
  title: string;
  check: string | null;
  ready: boolean | null;
  exit_code: number | null;
}

export interface DoctorReport {
  schema: number;
  name: string;
  manifest: string;
  commands: DoctorEntry[];
}

// `run_id` is generated by the caller (one per run_command invocation) and
// echoed back on every event, so the frontend can tell concurrent runs
// apart on the one shared `pult://run-output` channel — see
// src-tauri/src/types.rs's RunEvent doc comment.
//
// `step`/`progress`/`status` come from pult's `PULT_EVENTS` channel (the
// pult repo's docs/reference.md, "Events protocol — PULT_EVENTS"), which
// this app claims itself — see `run_streaming` in src-tauri/src/pult_bin.rs.
// Unix only: on Windows nothing sets `PULT_EVENTS`, so these three kinds
// simply never arrive there; stdout/stderr `line`s and the terminal `exit`
// still do.
export type RunEvent =
  | { kind: "line"; run_id: string; stream: "stdout" | "stderr"; text: string }
  | { kind: "step"; run_id: string; k: number; n: number; name: string }
  | { kind: "progress"; run_id: string; pct: number | null; text: string | null }
  | { kind: "status"; run_id: string; text: string }
  | { kind: "exit"; run_id: string; code: number | null; stopped: boolean };

/** A command's readiness lamp state, derived from doctor + trust.
 *  "no-check" is the confirmed case (doctor answered, `check:` is null) —
 *  distinct from "none", which means "nothing known yet" (doctor hasn't
 *  answered, or this command has no doctor entry at all). */
export type Readiness = "ready" | "failed" | "none" | "no-check" | "untrusted";
