// Typed mirrors of pult's documented JSON surfaces (schema 1), matching
// src-tauri/src/types.rs field-for-field. Schema 1 is additive-only, so
// every field here is exactly what the docs promise — extra fields a future
// pult adds are simply ignored by JSON.parse, not an error.

export interface Param {
  name: string;
  kind: "pick" | "input";
  options?: string[];
  source?: string;
  depends_on?: string[];
  default?: string | null;
  secret?: boolean;
}

export interface IncludeInfo {
  source: string;
  kind: string;
  name: string | null;
  url?: string;
  rev?: string;
  rev_kind?: string;
  resolved_sha?: string;
}

export interface CommandInfo {
  id: string;
  title: string;
  origin: string | null;
  category: string | null;
  /** Operator-facing one-liner for the board card. Additive field — may be
   *  absent or null; treat as "no description" (title-only card), not an
   *  error. */
  description?: string | null;
  params: Param[];
  check: string | null;
  interactive: boolean;
  steps: string[] | null;
}

export interface Listing {
  schema: number;
  pult_version: string;
  name: string;
  manifest: string;
  dir: string;
  run_dir: string;
  scope: string;
  trusted: boolean;
  includes: IncludeInfo[];
  commands: CommandInfo[];
}

export interface DoctorEntry {
  id: string;
  title: string;
  check: string | null;
  ready: boolean | null;
  exit_code: number | null;
}

export interface DoctorReport {
  schema: number;
  name: string;
  manifest: string;
  commands: DoctorEntry[];
}

// `run_id` is generated by the caller (one per run_command invocation) and
// echoed back on every event, so the frontend can tell concurrent runs
// apart on the one shared `pult://run-output` channel — see
// src-tauri/src/types.rs's RunEvent doc comment.
//
// `step`/`progress`/`status` come from pult's `PULT_EVENTS` channel (the
// pult repo's docs/reference.md, "Events protocol — PULT_EVENTS"), which
// this app claims itself — see `run_streaming` in src-tauri/src/pult_bin.rs.
// Unix only: on Windows nothing sets `PULT_EVENTS`, so these three kinds
// simply never arrive there; stdout/stderr `line`s and the terminal `exit`
// still do.
export type RunEvent =
  | { kind: "line"; run_id: string; stream: "stdout" | "stderr"; text: string }
  | { kind: "step"; run_id: string; k: number; n: number; name: string }
  | { kind: "progress"; run_id: string; pct: number | null; text: string | null }
  | { kind: "status"; run_id: string; text: string }
  | {
      kind: "exit";
      run_id: string;
      code: number | null;
      stopped: boolean;
      /** Reader-derived: the run's journal said "running" but the writing
       *  pult process was dead (crash detection) — never set on a journaled
       *  `exit` line itself, only synthesized when the tail never observes
       *  one. Additive field: absent/undefined means "not a crash", same as
       *  `false` (the mock backend's `runCommand` scripts never set it —
       *  only its canned crashed-history replay in `tailRun` does, purely to
       *  demo the crashed-rendering surface). */
      crashed?: boolean;
    };

export interface OutputLine {
  stream: "stdout" | "stderr" | "exit";
  text: string;
  /** Only set on the `exit` stream's line — which of the four summary forms
   *  it is (see `formatDuration`'s callers in +page.svelte), so renderers
   *  can color it without re-parsing `text`. `"crashed"` is its own kind,
   *  distinct from `"error"` (a normal nonzero exit) — pult's writer never
   *  recorded an exit at all, reader-derived (see `RunEvent`'s `exit.crashed`
   *  doc comment below). */
  outcome?: "success" | "error" | "stopped" | "crashed";
}

/** One `step` event, timestamped at arrival — the timestamp isn't part of
 *  the wire protocol (`RunEvent`'s `step` variant above), it's stamped
 *  locally the moment +page.svelte's event handler sees it, purely so the
 *  stage ladder can show a cheap "how long did that stage take" without the
 *  backend needing to report timing itself. */
export interface StepEvent {
  k: number;
  n: number;
  name: string;
  at: number;
}

// One run record per command id, kept above the board/run-view switch in
// +page.svelte so a running strip on the board and the run view's output
// pane both survive navigating back and forth, and so more than one command
// can run at once (each gets its own run_id — see `RunEvent` above).
//
// `step`/`stepHistory`/`progress`/`status` hold the latest (and, for steps,
// full history of) events of their kind from the PULT_EVENTS channel —
// additive alongside `lines`. `stopped` distinguishes a user-requested stop
// from a natural exit once `running` goes false; `crashed` is a third,
// mutually-exclusive-with-`stopped` terminal flavor — pult's writer died
// without ever journaling an exit (see `RunEvent`'s `exit.crashed` doc
// comment) — kept as its own field rather than folded into `exitCode` since
// a crash carries no exit code at all. `startedAt`/`endedAt` come from the
// journal once hydrated from a `RunSummary` (see +page.svelte's
// `recordFromSummary`), or are local wall-clock stamps for a run this
// session itself started — used for the details page's "started HH:MM:SS" /
// "elapsed M:SS" / "total M:SS" display either way.
export interface RunRecord {
  runId: string;
  running: boolean;
  lines: OutputLine[];
  step: StepEvent | null;
  stepHistory: StepEvent[];
  progress: { pct: number | null; text: string | null } | null;
  status: string | null;
  stopped: boolean;
  crashed: boolean;
  exitCode: number | null;
  startedAt: number;
  endedAt: number | null;
}

// One entry in `listRuns`'s result — the run journal's history for a repo
// (see docs/run-journal.md and src-tauri/src/journal.rs::RunSummary), newest
// first. `status` folds pult-desktop's reader-derived "crashed" detection in
// alongside the journal's own three writer-written statuses. This is a
// listing/history shape, not `RunRecord` (the live in-memory run the run
// view renders) — see +page.svelte's `recordFromSummary` for hydrating one
// into the other, and `startTail`/`tailRun` for pulling in its actual output.
export interface RunSummary {
  run_id: string;
  command_id: string;
  command_title: string;
  status: "running" | "exited" | "stopped" | "crashed";
  exit_code: number | null;
  started_at: string;
  ended_at: string | null;
  origin: string;
  interactive: boolean;
}

/** A command's readiness lamp state, derived from doctor + trust.
 *  "no-check" is the confirmed case (doctor answered, `check:` is null) —
 *  distinct from "none", which means "nothing known yet" (doctor hasn't
 *  answered, or this command has no doctor entry at all). */
export type Readiness = "ready" | "failed" | "none" | "no-check" | "untrusted";

// A repository mounted in the rack (design 4a) — the persisted list entry,
// not live state. `name`/`instruments`/`status` are a cache of the last
// successful/failed open so the rack can label a device without opening it:
// stale until the next `openRepo` of that path refreshes them.
export interface RackDevice {
  path: string;
  /** Display name — the listing's `name` once the device has been opened,
   *  the folder's basename until then. */
  name: string;
  /** Command count from the last open, or null before the first one. Shown
   *  as "N instruments" in the rack (the design's word for commands). */
  instruments: number | null;
  /** Outcome of the last open: null before the first attempt. "error" means
   *  `openRepo` itself failed (folder gone, no pult.yaml, …). */
  status: "ok" | "untrusted" | "error" | null;
}

export interface RackState {
  devices: RackDevice[];
  /** Path of the device that was active when last persisted — re-opened
   *  automatically on the next launch. Null when nothing was open. */
  activePath: string | null;
}
