//! The Tauri commands the frontend calls. Thin wrappers over `pult_bin`:
//! resolve the binary, run it, parse or translate its output. Every error
//! is a plain string the UI shows verbatim (operator-side copy, not
//! internals) per the product spec.

use std::collections::HashMap;

use tauri::{AppHandle, Emitter, State};

use crate::pult_bin::{
    resolve_pult, run_capture, run_streaming, set_stored_pult_path, stderr_text, stored_pult_path,
    RunRegistry,
};
use crate::types::{DoctorReport, Listing};

/// Open a repository: run `pult --list --json` there and parse the listing.
#[tauri::command]
pub async fn open_repo(app: AppHandle, path: String) -> Result<Listing, String> {
    let bin = resolve_pult(&app)?;
    let output = run_capture(&bin, &path, &["--list", "--json"], None).await?;

    if output.status.success() {
        serde_json::from_slice::<Listing>(&output.stdout)
            .map_err(|e| format!("Couldn't read this repository's commands: {e}"))
    } else {
        let stderr = stderr_text(&output);
        if stderr.contains("no pult.yaml found") {
            Err("No pult.yaml here — point me at a repository that has one".to_string())
        } else {
            Err(format!("Couldn't read this repository's commands: {stderr}"))
        }
    }
}

/// Trust a manifest at its current resolved hash: `pult --trust --list`.
/// The frontend re-calls `open_repo` afterward to reload with `trusted: true`.
#[tauri::command]
pub async fn trust_repo(app: AppHandle, path: String) -> Result<(), String> {
    let bin = resolve_pult(&app)?;
    let output = run_capture(&bin, &path, &["--trust", "--list"], None).await?;
    if output.status.success() {
        Ok(())
    } else {
        Err(format!(
            "Couldn't trust this repository: {}",
            stderr_text(&output)
        ))
    }
}

/// Run every command's `check:` and report readiness: `pult doctor --json`.
/// Trust-gated by pult itself — only call this once `open_repo` reports
/// `trusted: true`. Note doctor's own process exit code is 1 whenever any
/// check failed; that's expected and not an error, so we parse stdout first
/// and only fall back to an error if it isn't valid JSON.
#[tauri::command]
pub async fn doctor(app: AppHandle, path: String) -> Result<DoctorReport, String> {
    let bin = resolve_pult(&app)?;
    let output = run_capture(&bin, &path, &["doctor", "--json"], None).await?;

    if let Ok(report) = serde_json::from_slice::<DoctorReport>(&output.stdout) {
        return Ok(report);
    }
    Err(format!(
        "Couldn't check readiness: {}",
        stderr_text(&output)
    ))
}

/// `pult --version`.
#[tauri::command]
pub async fn pult_version(app: AppHandle) -> Result<String, String> {
    let bin = resolve_pult(&app)?;
    let dir = std::env::temp_dir();
    let output = run_capture(&bin, &dir.to_string_lossy(), &["--version"], None).await?;
    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        Err(format!(
            "Couldn't get pult's version: {}",
            stderr_text(&output)
        ))
    }
}

/// The currently configured `pult` path override, if any (not the resolved
/// binary — this is only what the user explicitly set in Settings).
#[tauri::command]
pub fn get_pult_path(app: AppHandle) -> Option<String> {
    stored_pult_path(&app)
}

/// Save a `pult` path override.
#[tauri::command]
pub fn set_pult_path(app: AppHandle, path: String) -> Result<(), String> {
    set_stored_pult_path(&app, &path)
}

/// Run a command: `pult <id> --params-json`, values fed on stdin (keeps
/// secrets out of argv, which is exactly why the flag exists). Streams
/// stdout/stderr lines — and, on unix, `PULT_EVENTS` step/progress/status
/// events — to the frontend as they arrive via the `pult://run-output`
/// event, then a final `Exit` event with the code. The actual spawn/stream/
/// stop machinery lives in `pult_bin::run_streaming` (kept `AppHandle`-free
/// so it's unit-testable — see its doc comment); this command just resolves
/// the binary and turns its callback into a Tauri event emission, the same
/// "thin wrapper" shape as every other command in this file.
///
/// `run_id` is generated by the caller (one per invocation) and echoed back
/// on every emitted event, so the frontend can run several commands at once
/// and still tell whose output is whose on the shared event channel; it's
/// also how `stop_run` below finds this run in `registry`.
#[tauri::command]
pub async fn run_command(
    app: AppHandle,
    registry: State<'_, RunRegistry>,
    path: String,
    id: String,
    run_id: String,
    values: HashMap<String, String>,
) -> Result<(), String> {
    let bin = resolve_pult(&app)?;
    let emit_app = app.clone();
    run_streaming(&bin, &path, &id, &values, run_id, &registry, move |event| {
        let _ = emit_app.emit("pult://run-output", event);
    })
    .await
}

/// Stop a running command started by `run_command`: `run_id` must match an
/// in-flight run tracked in `registry`. See `pult_bin::run_streaming`'s doc
/// comment for the actual stop semantics (process-group `SIGTERM` then
/// `SIGKILL` on unix after a grace period, `TerminateProcess` on Windows);
/// this command only has to find the run and ask.
#[tauri::command]
pub fn stop_run(registry: State<'_, RunRegistry>, run_id: String) -> Result<(), String> {
    registry.request_stop(&run_id)
}

/// Resolve a `pick.source` param's live options: `crate::pult_bin` does the
/// actual work (trust check, interpolation, shell-out) since it doesn't need
/// an `AppHandle` — this command just resolves the binary and delegates, the
/// same "thin wrapper" shape as every other command in this file.
#[tauri::command]
pub async fn resolve_pick_source(
    app: AppHandle,
    path: String,
    command_id: String,
    param_name: String,
    values: HashMap<String, String>,
) -> Result<Vec<String>, String> {
    let bin = resolve_pult(&app)?;
    crate::pult_bin::resolve_pick_source(&bin, &path, &command_id, &param_name, &values).await
}
