//! The Tauri commands the frontend calls. Thin wrappers over `pult_bin`:
//! resolve the binary, run it, parse or translate its output. Every error
//! is a plain string the UI shows verbatim (operator-side copy, not
//! internals) per the product spec.

use std::collections::HashMap;

use tauri::{AppHandle, State};

use crate::journal::{self, RunSummary, TailRegistry};
use crate::pult_bin::{
    resolve_pult, run_capture, set_stored_pult_path, stderr_text, stored_pult_path,
};
use crate::types::{DoctorReport, Listing};

/// Open a repository: run `pult --list --json` there and parse the listing.
#[tauri::command]
pub async fn open_repo(app: AppHandle, path: String) -> Result<Listing, String> {
    let bin = resolve_pult(&app)?;
    let output = run_capture(&bin, &path, &["--list", "--json"], None).await?;

    if output.status.success() {
        serde_json::from_slice::<Listing>(&output.stdout)
            .map_err(|e| format!("Couldn't read this repository's commands: {e}"))
    } else {
        let stderr = stderr_text(&output);
        if stderr.contains("no pult.yaml found") {
            Err("No pult.yaml here — point me at a repository that has one".to_string())
        } else {
            Err(format!(
                "Couldn't read this repository's commands: {stderr}"
            ))
        }
    }
}

/// Trust a manifest at its current resolved hash: `pult --trust --list`.
/// The frontend re-calls `open_repo` afterward to reload with `trusted: true`.
#[tauri::command]
pub async fn trust_repo(app: AppHandle, path: String) -> Result<(), String> {
    let bin = resolve_pult(&app)?;
    let output = run_capture(&bin, &path, &["--trust", "--list"], None).await?;
    if output.status.success() {
        Ok(())
    } else {
        Err(format!(
            "Couldn't trust this repository: {}",
            stderr_text(&output)
        ))
    }
}

/// Run every command's `check:` and report readiness: `pult doctor --json`.
/// Trust-gated by pult itself — only call this once `open_repo` reports
/// `trusted: true`. Note doctor's own process exit code is 1 whenever any
/// check failed; that's expected and not an error, so we parse stdout first
/// and only fall back to an error if it isn't valid JSON.
#[tauri::command]
pub async fn doctor(app: AppHandle, path: String) -> Result<DoctorReport, String> {
    let bin = resolve_pult(&app)?;
    let output = run_capture(&bin, &path, &["doctor", "--json"], None).await?;

    if let Ok(report) = serde_json::from_slice::<DoctorReport>(&output.stdout) {
        return Ok(report);
    }
    Err(format!(
        "Couldn't check readiness: {}",
        stderr_text(&output)
    ))
}

/// `pult --version`.
#[tauri::command]
pub async fn pult_version(app: AppHandle) -> Result<String, String> {
    let bin = resolve_pult(&app)?;
    let dir = std::env::temp_dir();
    let output = run_capture(&bin, &dir.to_string_lossy(), &["--version"], None).await?;
    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        Err(format!(
            "Couldn't get pult's version: {}",
            stderr_text(&output)
        ))
    }
}

/// The currently configured `pult` path override, if any (not the resolved
/// binary — this is only what the user explicitly set in Settings).
#[tauri::command]
pub fn get_pult_path(app: AppHandle) -> Option<String> {
    stored_pult_path(&app)
}

/// Save a `pult` path override.
#[tauri::command]
pub fn set_pult_path(app: AppHandle, path: String) -> Result<(), String> {
    set_stored_pult_path(&app, &path)
}

/// Run a command: `pult <id> --params-json --run-id <run_id>`, values fed on
/// stdin (keeps secrets out of argv, which is exactly why the flag exists),
/// spawned **detached** — pult journals everything itself now (see
/// `docs/run-journal.md`), so this app no longer pipes output or claims
/// `PULT_EVENTS`. The actual spawn lives in `pult_bin::spawn_run` (kept
/// `AppHandle`-free so it's unit-testable); this command returns as soon as
/// that returns, i.e. once the process is launched, not once it finishes.
///
/// Deliberately does NOT start a tail itself — the frontend's explicit
/// `tail_run` invoke (below) is the single tail-creation path for every run
/// source (a run started here, hydration, the CLI-visibility poll, a lazy
/// tail), so there's exactly one place that decides "start watching this
/// run_id" rather than two racing each other.
///
/// `run_id` is generated by the caller (one per invocation) and echoed back
/// on every emitted event, so the frontend can run several commands at once
/// and still tell whose output is whose on the shared event channel.
#[tauri::command]
pub async fn run_command(
    app: AppHandle,
    path: String,
    id: String,
    run_id: String,
    values: HashMap<String, String>,
) -> Result<(), String> {
    let bin = resolve_pult(&app)?;
    crate::pult_bin::spawn_run(&bin, &path, &id, &values, &run_id).await?;
    Ok(())
}

/// Stop a journaled run: reads `meta.json`'s `pgid` for `run_id` under
/// `path`'s journal and signals the group (`SIGTERM`, a grace period, then
/// `SIGKILL` if still alive) — see `journal::stop_run`'s doc comment. Works
/// identically for a run this app never spawned, since the stop capability
/// lives in the journal, not in any in-process registry.
#[tauri::command]
pub async fn stop_run(path: String, run_id: String) -> Result<(), String> {
    journal::stop_run(&path, &run_id).await
}

/// This repo's run history — every journaled run, newest first, with
/// reader-derived `"crashed"` folded into `status`. See
/// `journal::list_runs`'s doc comment.
#[tauri::command]
pub fn list_runs(path: String) -> Vec<RunSummary> {
    journal::list_runs(&path)
}

/// Start (or no-op if already started) tailing `run_id`'s journal, emitting
/// mapped events on the `pult://run-output` channel — the same channel
/// `run_command` uses, so hydrating a repo's run history and a freshly
/// spawned run are indistinguishable to the frontend once tailing begins.
#[tauri::command]
pub fn tail_run(app: AppHandle, tails: State<'_, TailRegistry>, path: String, run_id: String) {
    journal::tail_run(app, tails.inner().clone(), path, run_id);
}

/// Resolve a `pick.source` param's live options: `crate::pult_bin` does the
/// actual work (trust check, interpolation, shell-out) since it doesn't need
/// an `AppHandle` — this command just resolves the binary and delegates, the
/// same "thin wrapper" shape as every other command in this file.
#[tauri::command]
pub async fn resolve_pick_source(
    app: AppHandle,
    path: String,
    command_id: String,
    param_name: String,
    values: HashMap<String, String>,
) -> Result<Vec<String>, String> {
    let bin = resolve_pult(&app)?;
    crate::pult_bin::resolve_pick_source(&bin, &path, &command_id, &param_name, &values).await
}
